
CREATE TABLE public.generated_apis (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  source_url TEXT NOT NULL,
  api_endpoint TEXT NOT NULL,
  api_key TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.generated_apis IS 'Stores APIs generated by users.';

ALTER TABLE public.generated_apis ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own generated APIs"
  ON public.generated_apis
  FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own generated APIs"
  ON public.generated_apis
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

